name: alexapps_task
description: A new Flutter project with Clean Architecture by Yahai Samir
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  shared_preferences:
  flutter_screenutil:
  cupertino_icons:
  equatable: ^2.0.7
  flutter_svg:
  get_it: ^9.2.0
  dartz: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/jpg/
    - assets/icons/bottomNav/
    - assets/icons/appBar/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          style: italic
          weight: 300

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
          weight: 400

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
